/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEditOrderModal: typeof import('./src/components/modals/AddEditOrderModal.vue')['default']
    AddEditProductModal: typeof import('./src/components/modals/AddEditProductModal.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeleteOrderModal: typeof import('./src/components/modals/DeleteOrderModal.vue')['default']
    DeleteProductModal: typeof import('./src/components/modals/DeleteProductModal.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    Header: typeof import('./src/components/shared/Header.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OrderComponentTable: typeof import('./src/components/OrderComponentTable.vue')['default']
    ProductComponentTable: typeof import('./src/components/ProductComponentTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
